title: アプリ総合窓口
email: your-email@example.com
description: >
  アプリのサポート・紹介サイトです。
baseurl: "/kazunakka-repo"  # ← これを追加（リポジトリ名）
url: "https://kazunakka.github.io"  # ← これを追加（GitHubユーザー名）
# theme: minima
# plugins:
#   - jekyll-feed
